### ISSUE TITLE
Provide uninstall script

### ISSUE THREAD

**Issue by pensierinmusica** [nodequery/nq-agent#13]
Hi,

Thanks for developing Nodequery, looks really nice.

If I can suggest one improvement, it would be useful to provide an uninstall script too, that can be executed when one wants to delete the account.

Cheers!

**Comment by PontusTideman** [comment]
The accound on the site or the monitor agent on the server?

**Comment by pensierinmusica** [comment]
In this case I was referring to the monitor agent on the server.

**Comment by bdtech** [comment]
Tried this?

https://nodequery.com/help/remove-agent

**Comment by pensierinmusica** [comment]
Awesome thx!

**Comment by ddofborg** [comment]
The projects is dead :( Their website is down too so the link above does not work.

You can disable the agent from running with `sudo crontab -u nodequery -e` command and putting a `#` in front of the line `*/3 * * * * bash /etc/nodequery/nq-agent.sh > /etc/nodequery/nq-cron.log 2>&1`.

**Comment by n0099** [comment]
From https://web.archive.org/web/20210621171851/nodequery.com/help/remove-agent:

## Remove Agent
As soon as you delete a server from our interface, following command will be shown to remove the monitoring agent and any related data as well as user accounts from your system. Simply execute it as root on the server you don't want to monitor anymore.
```bash
rm -R /etc/nodequery && (crontab -u nodequery -l | grep -v "/etc/nodequery/nq-agent.sh") | crontab -u nodequery - && userdel nodequery
```
## Verifying Removal
To verify that everything was removed successfully, simply check if the directory /etc/nodequery and its owner account nodequery do not exist on your system anymore. If you are using an older version of the monitoring script, you might have to remove the cron entry with the user root instead of removing the account nodequery.
